item {
    name: "Car",
    id: 1,
    display_name: "Car"
}
item {
    name: "Person",
    id: 2,
    display_name: "Person"
}
item {
    name: "Stop_sign",
    id: 3,
    display_name: "Stop_sign"
}
